### ISSUE TITLE
Unable to read data from remote smb drive

### ISSUE THREAD

**Issue by shettypradeeph** [kwaxi/csvjdbc#6]
Hi,

I am facing problem while using csvdriver. Please help me out if I am doing anything wrong.

Scenario : In our project, we are downloading a zip file to remote folder. I need to read the data from a CSV file which is in the zip folder. I have used below code snippet.
//
Class.forName("org.relique.jdbc.csv.CsvDriver");
Connection conn = DriverManager.getConnection("smb://domainname;username:password@IP_ADDRESS_OF_SHAREDMACHINE/SHARED_PATH/abc.zip");
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            ResultSet results = stmt.executeQuery("SELECT * FROM questions where questionId='483840'");

       
            if (results.last()) {
                System.out.println("ID= " + results.toString() +
                        "   NAME= " + results.getString("hello"));

            }

It is throwing file not found exception. But If I connect to the remote drive machine using network and logged in and run the below code, it was working. Please help me out what to do?
//
Class.forName("org.relique.jdbc.csv.CsvDriver");
Connection conn = DriverManager.getConnection("//IP_ADDRESS_OF_SHAREDMACHINE/SHARED_PATH/abc.zip");
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            ResultSet results = stmt.executeQuery("SELECT * FROM questions where questionId='483840'");

            if (results.last()) {
                System.out.println("ID= " + results.toString() +
                        "   NAME= " + results.getString("hello"));

            }

**Comment by kwaxi** [comment]
Hi @shettypradeeph ,

you've to provide a proper JDBC connection string to DriverManager.getConnection. The simplest form is

```
jdbc:relique:csv:<path>
```

For full documentation look here: http://csvjdbc.sourceforge.net/doc.html

**Comment by shettypradeeph** [comment]
@kwaxi ,  could you please help me out in forming the jdbc url.

Suppose my file is located in  "//10.32.121.37/actual_exports/abc". I am giving below line of code

Connection conn = DriverManager.getConnection("jdbc:relique:csv:" + sFile.getUncPath());

It is giving directory not found exception. Could you please help me out
